# Generated by Django 3.2.9 on 2021-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firs_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=15)),
                ('qualification', models.BigIntegerField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
