# Generated by Django 3.2.9 on 2021-12-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('average_rating', models.FloatField(verbose_name='average rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('subject', models.CharField(max_length=64, verbose_name='subject')),
                ('salary', models.CharField(max_length=64, verbose_name='salary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
