# Generated by Django 3.2.9 on 2021-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='phone number'),
        ),
    ]
