# Generated by Django 3.2.9 on 2022-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0002_auto_20211226_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(to='groups.Group'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='groups.Group'),
        ),
    ]
