# Generated by Django 3.2.9 on 2022-01-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220119_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='group',
            new_name='groups',
        ),
    ]
